name: PlayTime
author: F64_Rx
version: ${project.version}
description: allows player to see how much they have played for.
main: me.f64.playtime.Main
api-version: 1.19
depend: [PlaceholderAPI]

commands:
  playtime:
    usage: /<command>
    aliases: [timeplayed, pt]
    description: Main command for Playtime!
